// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: card.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rank int32

const (
	Rank_TWO   Rank = 0
	Rank_THREE Rank = 1
	Rank_FOUR  Rank = 2
	Rank_FIVE  Rank = 3
	Rank_SIX   Rank = 4
	Rank_SEVEN Rank = 5
	Rank_EIGHT Rank = 6
	Rank_NINE  Rank = 7
	Rank_TEN   Rank = 8
	Rank_JACK  Rank = 9
	Rank_QUEEN Rank = 10
	Rank_KING  Rank = 11
	Rank_ACE   Rank = 12
)

// Enum value maps for Rank.
var (
	Rank_name = map[int32]string{
		0:  "TWO",
		1:  "THREE",
		2:  "FOUR",
		3:  "FIVE",
		4:  "SIX",
		5:  "SEVEN",
		6:  "EIGHT",
		7:  "NINE",
		8:  "TEN",
		9:  "JACK",
		10: "QUEEN",
		11: "KING",
		12: "ACE",
	}
	Rank_value = map[string]int32{
		"TWO":   0,
		"THREE": 1,
		"FOUR":  2,
		"FIVE":  3,
		"SIX":   4,
		"SEVEN": 5,
		"EIGHT": 6,
		"NINE":  7,
		"TEN":   8,
		"JACK":  9,
		"QUEEN": 10,
		"KING":  11,
		"ACE":   12,
	}
)

func (x Rank) Enum() *Rank {
	p := new(Rank)
	*p = x
	return p
}

func (x Rank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rank) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[0].Descriptor()
}

func (Rank) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[0]
}

func (x Rank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rank.Descriptor instead.
func (Rank) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

type Suit int32

const (
	Suit_HEARTS   Suit = 0
	Suit_DIAMONDS Suit = 1
	Suit_SPADES   Suit = 2
	Suit_CLUBS    Suit = 3
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "HEARTS",
		1: "DIAMONDS",
		2: "SPADES",
		3: "CLUBS",
	}
	Suit_value = map[string]int32{
		"HEARTS":   0,
		"DIAMONDS": 1,
		"SPADES":   2,
		"CLUBS":    3,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[1].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[1]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

type HandStrength int32

const (
	HandStrength_UNSET          HandStrength = 0
	HandStrength_HIGH_CARD      HandStrength = 1
	HandStrength_PAIR           HandStrength = 2
	HandStrength_TWO_PAIR       HandStrength = 3
	HandStrength_TRIPS          HandStrength = 4
	HandStrength_STRAIGHT       HandStrength = 5
	HandStrength_FLUSH          HandStrength = 6
	HandStrength_FULL_HOUSE     HandStrength = 7
	HandStrength_QUADS          HandStrength = 8
	HandStrength_STRAIGHT_FLUSH HandStrength = 9
)

// Enum value maps for HandStrength.
var (
	HandStrength_name = map[int32]string{
		0: "UNSET",
		1: "HIGH_CARD",
		2: "PAIR",
		3: "TWO_PAIR",
		4: "TRIPS",
		5: "STRAIGHT",
		6: "FLUSH",
		7: "FULL_HOUSE",
		8: "QUADS",
		9: "STRAIGHT_FLUSH",
	}
	HandStrength_value = map[string]int32{
		"UNSET":          0,
		"HIGH_CARD":      1,
		"PAIR":           2,
		"TWO_PAIR":       3,
		"TRIPS":          4,
		"STRAIGHT":       5,
		"FLUSH":          6,
		"FULL_HOUSE":     7,
		"QUADS":          8,
		"STRAIGHT_FLUSH": 9,
	}
)

func (x HandStrength) Enum() *HandStrength {
	p := new(HandStrength)
	*p = x
	return p
}

func (x HandStrength) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandStrength) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[2].Descriptor()
}

func (HandStrength) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[2]
}

func (x HandStrength) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandStrength.Descriptor instead.
func (HandStrength) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rank Rank `protobuf:"varint,1,opt,name=rank,proto3,enum=thegamblr.Rank" json:"rank,omitempty"`
	Suit Suit `protobuf:"varint,2,opt,name=suit,proto3,enum=thegamblr.Suit" json:"suit,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetRank() Rank {
	if x != nil {
		return x.Rank
	}
	return Rank_TWO
}

func (x *Card) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_HEARTS
}

var File_card_proto protoreflect.FileDescriptor

var file_card_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x68,
	0x65, 0x67, 0x61, 0x6d, 0x62, 0x6c, 0x72, 0x22, 0x50, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x23, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x74, 0x68, 0x65, 0x67, 0x61, 0x6d, 0x62, 0x6c, 0x72, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x75, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x74, 0x68, 0x65, 0x67, 0x61, 0x6d, 0x62, 0x6c, 0x72, 0x2e, 0x53,
	0x75, 0x69, 0x74, 0x52, 0x04, 0x73, 0x75, 0x69, 0x74, 0x2a, 0x88, 0x01, 0x0a, 0x04, 0x52, 0x61,
	0x6e, 0x6b, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x57, 0x4f, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54,
	0x48, 0x52, 0x45, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4f, 0x55, 0x52, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x56, 0x45, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x49,
	0x58, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x45, 0x56, 0x45, 0x4e, 0x10, 0x05, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x49, 0x47, 0x48, 0x54, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x49, 0x4e,
	0x45, 0x10, 0x07, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x45, 0x4e, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04,
	0x4a, 0x41, 0x43, 0x4b, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x45, 0x4e, 0x10,
	0x0a, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x0b, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x43, 0x45, 0x10, 0x0c, 0x2a, 0x37, 0x0a, 0x04, 0x53, 0x75, 0x69, 0x74, 0x12, 0x0a, 0x0a, 0x06,
	0x48, 0x45, 0x41, 0x52, 0x54, 0x53, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x41, 0x4d,
	0x4f, 0x4e, 0x44, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x50, 0x41, 0x44, 0x45, 0x53,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x55, 0x42, 0x53, 0x10, 0x03, 0x2a, 0x93, 0x01,
	0x0a, 0x0c, 0x48, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x09,
	0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x49, 0x47,
	0x48, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x49, 0x52,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x57, 0x4f, 0x5f, 0x50, 0x41, 0x49, 0x52, 0x10, 0x03,
	0x12, 0x09, 0x0a, 0x05, 0x54, 0x52, 0x49, 0x50, 0x53, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x53,
	0x54, 0x52, 0x41, 0x49, 0x47, 0x48, 0x54, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x55,
	0x53, 0x48, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x55, 0x4c, 0x4c, 0x5f, 0x48, 0x4f, 0x55,
	0x53, 0x45, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x41, 0x44, 0x53, 0x10, 0x08, 0x12,
	0x12, 0x0a, 0x0e, 0x53, 0x54, 0x52, 0x41, 0x49, 0x47, 0x48, 0x54, 0x5f, 0x46, 0x4c, 0x55, 0x53,
	0x48, 0x10, 0x09, 0x42, 0x11, 0x5a, 0x0f, 0x74, 0x68, 0x65, 0x67, 0x61, 0x6d, 0x62, 0x6c, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData = file_card_proto_rawDesc
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_card_proto_rawDescData)
	})
	return file_card_proto_rawDescData
}

var file_card_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_card_proto_goTypes = []interface{}{
	(Rank)(0),         // 0: thegamblr.Rank
	(Suit)(0),         // 1: thegamblr.Suit
	(HandStrength)(0), // 2: thegamblr.HandStrength
	(*Card)(nil),      // 3: thegamblr.Card
}
var file_card_proto_depIdxs = []int32{
	0, // 0: thegamblr.Card.rank:type_name -> thegamblr.Rank
	1, // 1: thegamblr.Card.suit:type_name -> thegamblr.Suit
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_card_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		EnumInfos:         file_card_proto_enumTypes,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_rawDesc = nil
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
