// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: card.proto

package thegamblr;

public final class CardOuterClass {
  private CardOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code thegamblr.Rank}
   */
  public enum Rank
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TWO = 0;</code>
     */
    TWO(0),
    /**
     * <code>THREE = 1;</code>
     */
    THREE(1),
    /**
     * <code>FOUR = 2;</code>
     */
    FOUR(2),
    /**
     * <code>FIVE = 3;</code>
     */
    FIVE(3),
    /**
     * <code>SIX = 4;</code>
     */
    SIX(4),
    /**
     * <code>SEVEN = 5;</code>
     */
    SEVEN(5),
    /**
     * <code>EIGHT = 6;</code>
     */
    EIGHT(6),
    /**
     * <code>NINE = 7;</code>
     */
    NINE(7),
    /**
     * <code>TEN = 8;</code>
     */
    TEN(8),
    /**
     * <code>JACK = 9;</code>
     */
    JACK(9),
    /**
     * <code>QUEEN = 10;</code>
     */
    QUEEN(10),
    /**
     * <code>KING = 11;</code>
     */
    KING(11),
    /**
     * <code>ACE = 12;</code>
     */
    ACE(12),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TWO = 0;</code>
     */
    public static final int TWO_VALUE = 0;
    /**
     * <code>THREE = 1;</code>
     */
    public static final int THREE_VALUE = 1;
    /**
     * <code>FOUR = 2;</code>
     */
    public static final int FOUR_VALUE = 2;
    /**
     * <code>FIVE = 3;</code>
     */
    public static final int FIVE_VALUE = 3;
    /**
     * <code>SIX = 4;</code>
     */
    public static final int SIX_VALUE = 4;
    /**
     * <code>SEVEN = 5;</code>
     */
    public static final int SEVEN_VALUE = 5;
    /**
     * <code>EIGHT = 6;</code>
     */
    public static final int EIGHT_VALUE = 6;
    /**
     * <code>NINE = 7;</code>
     */
    public static final int NINE_VALUE = 7;
    /**
     * <code>TEN = 8;</code>
     */
    public static final int TEN_VALUE = 8;
    /**
     * <code>JACK = 9;</code>
     */
    public static final int JACK_VALUE = 9;
    /**
     * <code>QUEEN = 10;</code>
     */
    public static final int QUEEN_VALUE = 10;
    /**
     * <code>KING = 11;</code>
     */
    public static final int KING_VALUE = 11;
    /**
     * <code>ACE = 12;</code>
     */
    public static final int ACE_VALUE = 12;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Rank valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Rank forNumber(int value) {
      switch (value) {
        case 0: return TWO;
        case 1: return THREE;
        case 2: return FOUR;
        case 3: return FIVE;
        case 4: return SIX;
        case 5: return SEVEN;
        case 6: return EIGHT;
        case 7: return NINE;
        case 8: return TEN;
        case 9: return JACK;
        case 10: return QUEEN;
        case 11: return KING;
        case 12: return ACE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Rank>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Rank> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Rank>() {
            public Rank findValueByNumber(int number) {
              return Rank.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return thegamblr.CardOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Rank[] VALUES = values();

    public static Rank valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Rank(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:thegamblr.Rank)
  }

  /**
   * Protobuf enum {@code thegamblr.Suit}
   */
  public enum Suit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTS = 0;</code>
     */
    HEARTS(0),
    /**
     * <code>DIAMONDS = 1;</code>
     */
    DIAMONDS(1),
    /**
     * <code>SPADES = 2;</code>
     */
    SPADES(2),
    /**
     * <code>CLUBS = 3;</code>
     */
    CLUBS(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HEARTS = 0;</code>
     */
    public static final int HEARTS_VALUE = 0;
    /**
     * <code>DIAMONDS = 1;</code>
     */
    public static final int DIAMONDS_VALUE = 1;
    /**
     * <code>SPADES = 2;</code>
     */
    public static final int SPADES_VALUE = 2;
    /**
     * <code>CLUBS = 3;</code>
     */
    public static final int CLUBS_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Suit valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Suit forNumber(int value) {
      switch (value) {
        case 0: return HEARTS;
        case 1: return DIAMONDS;
        case 2: return SPADES;
        case 3: return CLUBS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Suit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Suit> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Suit>() {
            public Suit findValueByNumber(int number) {
              return Suit.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return thegamblr.CardOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final Suit[] VALUES = values();

    public static Suit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Suit(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:thegamblr.Suit)
  }

  /**
   * Protobuf enum {@code thegamblr.HandStrength}
   */
  public enum HandStrength
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSET = 0;</code>
     */
    UNSET(0),
    /**
     * <code>HIGH_CARD = 1;</code>
     */
    HIGH_CARD(1),
    /**
     * <code>PAIR = 2;</code>
     */
    PAIR(2),
    /**
     * <code>TWO_PAIR = 3;</code>
     */
    TWO_PAIR(3),
    /**
     * <code>TRIPS = 4;</code>
     */
    TRIPS(4),
    /**
     * <code>STRAIGHT = 5;</code>
     */
    STRAIGHT(5),
    /**
     * <code>FLUSH = 6;</code>
     */
    FLUSH(6),
    /**
     * <code>FULL_HOUSE = 7;</code>
     */
    FULL_HOUSE(7),
    /**
     * <code>QUADS = 8;</code>
     */
    QUADS(8),
    /**
     * <code>STRAIGHT_FLUSH = 9;</code>
     */
    STRAIGHT_FLUSH(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSET = 0;</code>
     */
    public static final int UNSET_VALUE = 0;
    /**
     * <code>HIGH_CARD = 1;</code>
     */
    public static final int HIGH_CARD_VALUE = 1;
    /**
     * <code>PAIR = 2;</code>
     */
    public static final int PAIR_VALUE = 2;
    /**
     * <code>TWO_PAIR = 3;</code>
     */
    public static final int TWO_PAIR_VALUE = 3;
    /**
     * <code>TRIPS = 4;</code>
     */
    public static final int TRIPS_VALUE = 4;
    /**
     * <code>STRAIGHT = 5;</code>
     */
    public static final int STRAIGHT_VALUE = 5;
    /**
     * <code>FLUSH = 6;</code>
     */
    public static final int FLUSH_VALUE = 6;
    /**
     * <code>FULL_HOUSE = 7;</code>
     */
    public static final int FULL_HOUSE_VALUE = 7;
    /**
     * <code>QUADS = 8;</code>
     */
    public static final int QUADS_VALUE = 8;
    /**
     * <code>STRAIGHT_FLUSH = 9;</code>
     */
    public static final int STRAIGHT_FLUSH_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HandStrength valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HandStrength forNumber(int value) {
      switch (value) {
        case 0: return UNSET;
        case 1: return HIGH_CARD;
        case 2: return PAIR;
        case 3: return TWO_PAIR;
        case 4: return TRIPS;
        case 5: return STRAIGHT;
        case 6: return FLUSH;
        case 7: return FULL_HOUSE;
        case 8: return QUADS;
        case 9: return STRAIGHT_FLUSH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HandStrength>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HandStrength> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HandStrength>() {
            public HandStrength findValueByNumber(int number) {
              return HandStrength.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return thegamblr.CardOuterClass.getDescriptor().getEnumTypes().get(2);
    }

    private static final HandStrength[] VALUES = values();

    public static HandStrength valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HandStrength(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:thegamblr.HandStrength)
  }

  public interface CardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:thegamblr.Card)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.thegamblr.Rank rank = 1;</code>
     * @return The enum numeric value on the wire for rank.
     */
    int getRankValue();
    /**
     * <code>.thegamblr.Rank rank = 1;</code>
     * @return The rank.
     */
    thegamblr.CardOuterClass.Rank getRank();

    /**
     * <code>.thegamblr.Suit suit = 2;</code>
     * @return The enum numeric value on the wire for suit.
     */
    int getSuitValue();
    /**
     * <code>.thegamblr.Suit suit = 2;</code>
     * @return The suit.
     */
    thegamblr.CardOuterClass.Suit getSuit();
  }
  /**
   * Protobuf type {@code thegamblr.Card}
   */
  public static final class Card extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:thegamblr.Card)
      CardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Card.newBuilder() to construct.
    private Card(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Card() {
      rank_ = 0;
      suit_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Card();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Card(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              rank_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              suit_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return thegamblr.CardOuterClass.internal_static_thegamblr_Card_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return thegamblr.CardOuterClass.internal_static_thegamblr_Card_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              thegamblr.CardOuterClass.Card.class, thegamblr.CardOuterClass.Card.Builder.class);
    }

    public static final int RANK_FIELD_NUMBER = 1;
    private int rank_;
    /**
     * <code>.thegamblr.Rank rank = 1;</code>
     * @return The enum numeric value on the wire for rank.
     */
    @java.lang.Override public int getRankValue() {
      return rank_;
    }
    /**
     * <code>.thegamblr.Rank rank = 1;</code>
     * @return The rank.
     */
    @java.lang.Override public thegamblr.CardOuterClass.Rank getRank() {
      @SuppressWarnings("deprecation")
      thegamblr.CardOuterClass.Rank result = thegamblr.CardOuterClass.Rank.valueOf(rank_);
      return result == null ? thegamblr.CardOuterClass.Rank.UNRECOGNIZED : result;
    }

    public static final int SUIT_FIELD_NUMBER = 2;
    private int suit_;
    /**
     * <code>.thegamblr.Suit suit = 2;</code>
     * @return The enum numeric value on the wire for suit.
     */
    @java.lang.Override public int getSuitValue() {
      return suit_;
    }
    /**
     * <code>.thegamblr.Suit suit = 2;</code>
     * @return The suit.
     */
    @java.lang.Override public thegamblr.CardOuterClass.Suit getSuit() {
      @SuppressWarnings("deprecation")
      thegamblr.CardOuterClass.Suit result = thegamblr.CardOuterClass.Suit.valueOf(suit_);
      return result == null ? thegamblr.CardOuterClass.Suit.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rank_ != thegamblr.CardOuterClass.Rank.TWO.getNumber()) {
        output.writeEnum(1, rank_);
      }
      if (suit_ != thegamblr.CardOuterClass.Suit.HEARTS.getNumber()) {
        output.writeEnum(2, suit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rank_ != thegamblr.CardOuterClass.Rank.TWO.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, rank_);
      }
      if (suit_ != thegamblr.CardOuterClass.Suit.HEARTS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, suit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof thegamblr.CardOuterClass.Card)) {
        return super.equals(obj);
      }
      thegamblr.CardOuterClass.Card other = (thegamblr.CardOuterClass.Card) obj;

      if (rank_ != other.rank_) return false;
      if (suit_ != other.suit_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RANK_FIELD_NUMBER;
      hash = (53 * hash) + rank_;
      hash = (37 * hash) + SUIT_FIELD_NUMBER;
      hash = (53 * hash) + suit_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static thegamblr.CardOuterClass.Card parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static thegamblr.CardOuterClass.Card parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static thegamblr.CardOuterClass.Card parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static thegamblr.CardOuterClass.Card parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(thegamblr.CardOuterClass.Card prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code thegamblr.Card}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:thegamblr.Card)
        thegamblr.CardOuterClass.CardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return thegamblr.CardOuterClass.internal_static_thegamblr_Card_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return thegamblr.CardOuterClass.internal_static_thegamblr_Card_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                thegamblr.CardOuterClass.Card.class, thegamblr.CardOuterClass.Card.Builder.class);
      }

      // Construct using thegamblr.CardOuterClass.Card.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rank_ = 0;

        suit_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return thegamblr.CardOuterClass.internal_static_thegamblr_Card_descriptor;
      }

      @java.lang.Override
      public thegamblr.CardOuterClass.Card getDefaultInstanceForType() {
        return thegamblr.CardOuterClass.Card.getDefaultInstance();
      }

      @java.lang.Override
      public thegamblr.CardOuterClass.Card build() {
        thegamblr.CardOuterClass.Card result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public thegamblr.CardOuterClass.Card buildPartial() {
        thegamblr.CardOuterClass.Card result = new thegamblr.CardOuterClass.Card(this);
        result.rank_ = rank_;
        result.suit_ = suit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof thegamblr.CardOuterClass.Card) {
          return mergeFrom((thegamblr.CardOuterClass.Card)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(thegamblr.CardOuterClass.Card other) {
        if (other == thegamblr.CardOuterClass.Card.getDefaultInstance()) return this;
        if (other.rank_ != 0) {
          setRankValue(other.getRankValue());
        }
        if (other.suit_ != 0) {
          setSuitValue(other.getSuitValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        thegamblr.CardOuterClass.Card parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (thegamblr.CardOuterClass.Card) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rank_ = 0;
      /**
       * <code>.thegamblr.Rank rank = 1;</code>
       * @return The enum numeric value on the wire for rank.
       */
      @java.lang.Override public int getRankValue() {
        return rank_;
      }
      /**
       * <code>.thegamblr.Rank rank = 1;</code>
       * @param value The enum numeric value on the wire for rank to set.
       * @return This builder for chaining.
       */
      public Builder setRankValue(int value) {
        
        rank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.thegamblr.Rank rank = 1;</code>
       * @return The rank.
       */
      @java.lang.Override
      public thegamblr.CardOuterClass.Rank getRank() {
        @SuppressWarnings("deprecation")
        thegamblr.CardOuterClass.Rank result = thegamblr.CardOuterClass.Rank.valueOf(rank_);
        return result == null ? thegamblr.CardOuterClass.Rank.UNRECOGNIZED : result;
      }
      /**
       * <code>.thegamblr.Rank rank = 1;</code>
       * @param value The rank to set.
       * @return This builder for chaining.
       */
      public Builder setRank(thegamblr.CardOuterClass.Rank value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        rank_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.thegamblr.Rank rank = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRank() {
        
        rank_ = 0;
        onChanged();
        return this;
      }

      private int suit_ = 0;
      /**
       * <code>.thegamblr.Suit suit = 2;</code>
       * @return The enum numeric value on the wire for suit.
       */
      @java.lang.Override public int getSuitValue() {
        return suit_;
      }
      /**
       * <code>.thegamblr.Suit suit = 2;</code>
       * @param value The enum numeric value on the wire for suit to set.
       * @return This builder for chaining.
       */
      public Builder setSuitValue(int value) {
        
        suit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.thegamblr.Suit suit = 2;</code>
       * @return The suit.
       */
      @java.lang.Override
      public thegamblr.CardOuterClass.Suit getSuit() {
        @SuppressWarnings("deprecation")
        thegamblr.CardOuterClass.Suit result = thegamblr.CardOuterClass.Suit.valueOf(suit_);
        return result == null ? thegamblr.CardOuterClass.Suit.UNRECOGNIZED : result;
      }
      /**
       * <code>.thegamblr.Suit suit = 2;</code>
       * @param value The suit to set.
       * @return This builder for chaining.
       */
      public Builder setSuit(thegamblr.CardOuterClass.Suit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        suit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.thegamblr.Suit suit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuit() {
        
        suit_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:thegamblr.Card)
    }

    // @@protoc_insertion_point(class_scope:thegamblr.Card)
    private static final thegamblr.CardOuterClass.Card DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new thegamblr.CardOuterClass.Card();
    }

    public static thegamblr.CardOuterClass.Card getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Card>
        PARSER = new com.google.protobuf.AbstractParser<Card>() {
      @java.lang.Override
      public Card parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Card(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Card> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Card> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public thegamblr.CardOuterClass.Card getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_thegamblr_Card_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_thegamblr_Card_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncard.proto\022\tthegamblr\"D\n\004Card\022\035\n\004rank\030" +
      "\001 \001(\0162\017.thegamblr.Rank\022\035\n\004suit\030\002 \001(\0162\017.t" +
      "hegamblr.Suit*\210\001\n\004Rank\022\007\n\003TWO\020\000\022\t\n\005THREE" +
      "\020\001\022\010\n\004FOUR\020\002\022\010\n\004FIVE\020\003\022\007\n\003SIX\020\004\022\t\n\005SEVEN" +
      "\020\005\022\t\n\005EIGHT\020\006\022\010\n\004NINE\020\007\022\007\n\003TEN\020\010\022\010\n\004JACK" +
      "\020\t\022\t\n\005QUEEN\020\n\022\010\n\004KING\020\013\022\007\n\003ACE\020\014*7\n\004Suit" +
      "\022\n\n\006HEARTS\020\000\022\014\n\010DIAMONDS\020\001\022\n\n\006SPADES\020\002\022\t" +
      "\n\005CLUBS\020\003*\223\001\n\014HandStrength\022\t\n\005UNSET\020\000\022\r\n" +
      "\tHIGH_CARD\020\001\022\010\n\004PAIR\020\002\022\014\n\010TWO_PAIR\020\003\022\t\n\005" +
      "TRIPS\020\004\022\014\n\010STRAIGHT\020\005\022\t\n\005FLUSH\020\006\022\016\n\nFULL" +
      "_HOUSE\020\007\022\t\n\005QUADS\020\010\022\022\n\016STRAIGHT_FLUSH\020\tB" +
      "\021Z\017thegamblr/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_thegamblr_Card_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_thegamblr_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_thegamblr_Card_descriptor,
        new java.lang.String[] { "Rank", "Suit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
