// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stage.proto

package thegamblr;

public final class StageOuterClass {
  private StageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code thegamblr.Stage}
   */
  public enum Stage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PRE_FLOP = 0;</code>
     */
    PRE_FLOP(0),
    /**
     * <code>FLOP = 1;</code>
     */
    FLOP(1),
    /**
     * <code>TURN = 2;</code>
     */
    TURN(2),
    /**
     * <code>RIVER = 3;</code>
     */
    RIVER(3),
    /**
     * <code>ROUND_COMPLETE = 4;</code>
     */
    ROUND_COMPLETE(4),
    /**
     * <code>GAME_COMPLETE = 5;</code>
     */
    GAME_COMPLETE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PRE_FLOP = 0;</code>
     */
    public static final int PRE_FLOP_VALUE = 0;
    /**
     * <code>FLOP = 1;</code>
     */
    public static final int FLOP_VALUE = 1;
    /**
     * <code>TURN = 2;</code>
     */
    public static final int TURN_VALUE = 2;
    /**
     * <code>RIVER = 3;</code>
     */
    public static final int RIVER_VALUE = 3;
    /**
     * <code>ROUND_COMPLETE = 4;</code>
     */
    public static final int ROUND_COMPLETE_VALUE = 4;
    /**
     * <code>GAME_COMPLETE = 5;</code>
     */
    public static final int GAME_COMPLETE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Stage valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Stage forNumber(int value) {
      switch (value) {
        case 0: return PRE_FLOP;
        case 1: return FLOP;
        case 2: return TURN;
        case 3: return RIVER;
        case 4: return ROUND_COMPLETE;
        case 5: return GAME_COMPLETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Stage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Stage> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Stage>() {
            public Stage findValueByNumber(int number) {
              return Stage.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return thegamblr.StageOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Stage[] VALUES = values();

    public static Stage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Stage(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:thegamblr.Stage)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013stage.proto\022\tthegamblr*[\n\005Stage\022\014\n\010PRE" +
      "_FLOP\020\000\022\010\n\004FLOP\020\001\022\010\n\004TURN\020\002\022\t\n\005RIVER\020\003\022\022" +
      "\n\016ROUND_COMPLETE\020\004\022\021\n\rGAME_COMPLETE\020\005B\021Z" +
      "\017thegamblr/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
