# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import player_state_pb2 as player__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x12\tthegamblr\x1a\x12player_state.proto\"e\n\x06\x41\x63tion\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.thegamblr.ActionType\x12&\n\x06player\x18\x02 \x01(\x0b\x32\x16.thegamblr.PlayerState\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04*[\n\nActionType\x12\x08\n\x04\x46OLD\x10\x00\x12\x08\n\x04\x43\x41LL\x10\x01\x12\t\n\x05RAISE\x10\x02\x12\x0e\n\nCHECK_FOLD\x10\x03\x12\x0f\n\x0bSMALL_BLIND\x10\x04\x12\r\n\tBIG_BLIND\x10\x05\x42\x11Z\x0fthegamblr/protob\x06proto3')

_ACTIONTYPE = DESCRIPTOR.enum_types_by_name['ActionType']
ActionType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTYPE)
FOLD = 0
CALL = 1
RAISE = 2
CHECK_FOLD = 3
SMALL_BLIND = 4
BIG_BLIND = 5


_ACTION = DESCRIPTOR.message_types_by_name['Action']
Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'action_pb2'
  # @@protoc_insertion_point(class_scope:thegamblr.Action)
  })
_sym_db.RegisterMessage(Action)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017thegamblr/proto'
  _ACTIONTYPE._serialized_start=150
  _ACTIONTYPE._serialized_end=241
  _ACTION._serialized_start=47
  _ACTION._serialized_end=148
# @@protoc_insertion_point(module_scope)
