# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncard.proto\x12\tthegamblr\"D\n\x04\x43\x61rd\x12\x1d\n\x04rank\x18\x01 \x01(\x0e\x32\x0f.thegamblr.Rank\x12\x1d\n\x04suit\x18\x02 \x01(\x0e\x32\x0f.thegamblr.Suit*\x88\x01\n\x04Rank\x12\x07\n\x03TWO\x10\x00\x12\t\n\x05THREE\x10\x01\x12\x08\n\x04\x46OUR\x10\x02\x12\x08\n\x04\x46IVE\x10\x03\x12\x07\n\x03SIX\x10\x04\x12\t\n\x05SEVEN\x10\x05\x12\t\n\x05\x45IGHT\x10\x06\x12\x08\n\x04NINE\x10\x07\x12\x07\n\x03TEN\x10\x08\x12\x08\n\x04JACK\x10\t\x12\t\n\x05QUEEN\x10\n\x12\x08\n\x04KING\x10\x0b\x12\x07\n\x03\x41\x43\x45\x10\x0c*7\n\x04Suit\x12\n\n\x06HEARTS\x10\x00\x12\x0c\n\x08\x44IAMONDS\x10\x01\x12\n\n\x06SPADES\x10\x02\x12\t\n\x05\x43LUBS\x10\x03*\x93\x01\n\x0cHandStrength\x12\t\n\x05UNSET\x10\x00\x12\r\n\tHIGH_CARD\x10\x01\x12\x08\n\x04PAIR\x10\x02\x12\x0c\n\x08TWO_PAIR\x10\x03\x12\t\n\x05TRIPS\x10\x04\x12\x0c\n\x08STRAIGHT\x10\x05\x12\t\n\x05\x46LUSH\x10\x06\x12\x0e\n\nFULL_HOUSE\x10\x07\x12\t\n\x05QUADS\x10\x08\x12\x12\n\x0eSTRAIGHT_FLUSH\x10\tB\x11Z\x0fthegamblr/protob\x06proto3')

_RANK = DESCRIPTOR.enum_types_by_name['Rank']
Rank = enum_type_wrapper.EnumTypeWrapper(_RANK)
_SUIT = DESCRIPTOR.enum_types_by_name['Suit']
Suit = enum_type_wrapper.EnumTypeWrapper(_SUIT)
_HANDSTRENGTH = DESCRIPTOR.enum_types_by_name['HandStrength']
HandStrength = enum_type_wrapper.EnumTypeWrapper(_HANDSTRENGTH)
TWO = 0
THREE = 1
FOUR = 2
FIVE = 3
SIX = 4
SEVEN = 5
EIGHT = 6
NINE = 7
TEN = 8
JACK = 9
QUEEN = 10
KING = 11
ACE = 12
HEARTS = 0
DIAMONDS = 1
SPADES = 2
CLUBS = 3
UNSET = 0
HIGH_CARD = 1
PAIR = 2
TWO_PAIR = 3
TRIPS = 4
STRAIGHT = 5
FLUSH = 6
FULL_HOUSE = 7
QUADS = 8
STRAIGHT_FLUSH = 9


_CARD = DESCRIPTOR.message_types_by_name['Card']
Card = _reflection.GeneratedProtocolMessageType('Card', (_message.Message,), {
  'DESCRIPTOR' : _CARD,
  '__module__' : 'card_pb2'
  # @@protoc_insertion_point(class_scope:thegamblr.Card)
  })
_sym_db.RegisterMessage(Card)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017thegamblr/proto'
  _RANK._serialized_start=96
  _RANK._serialized_end=232
  _SUIT._serialized_start=234
  _SUIT._serialized_end=289
  _HANDSTRENGTH._serialized_start=292
  _HANDSTRENGTH._serialized_end=439
  _CARD._serialized_start=25
  _CARD._serialized_end=93
# @@protoc_insertion_point(module_scope)
