# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import card_pb2 as card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12player_state.proto\x12\tthegamblr\x1a\ncard.proto\"w\n\x12PlayerRoundResults\x12\x11\n\tchips_won\x18\x01 \x01(\x04\x12\x1e\n\x05\x63\x61rds\x18\x02 \x03(\x0b\x32\x0f.thegamblr.Card\x12.\n\rhand_strength\x18\x03 \x01(\x0e\x32\x17.thegamblr.HandStrength\"\x9c\x01\n\x0bPlayerState\x12\r\n\x05stack\x18\x01 \x01(\x04\x12\'\n\x06status\x18\x02 \x01(\x0e\x32\x17.thegamblr.PlayerStatus\x12\x13\n\x0bseat_number\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\t\x12\x34\n\rround_results\x18\x05 \x01(\x0b\x32\x1d.thegamblr.PlayerRoundResults*<\n\x0cPlayerStatus\x12\x07\n\x03OUT\x10\x00\x12\n\n\x06\x46OLDED\x10\x01\x12\x0b\n\x07PLAYING\x10\x02\x12\n\n\x06\x41LL_IN\x10\x03\x42\x11Z\x0fthegamblr/protob\x06proto3')

_PLAYERSTATUS = DESCRIPTOR.enum_types_by_name['PlayerStatus']
PlayerStatus = enum_type_wrapper.EnumTypeWrapper(_PLAYERSTATUS)
OUT = 0
FOLDED = 1
PLAYING = 2
ALL_IN = 3


_PLAYERROUNDRESULTS = DESCRIPTOR.message_types_by_name['PlayerRoundResults']
_PLAYERSTATE = DESCRIPTOR.message_types_by_name['PlayerState']
PlayerRoundResults = _reflection.GeneratedProtocolMessageType('PlayerRoundResults', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERROUNDRESULTS,
  '__module__' : 'player_state_pb2'
  # @@protoc_insertion_point(class_scope:thegamblr.PlayerRoundResults)
  })
_sym_db.RegisterMessage(PlayerRoundResults)

PlayerState = _reflection.GeneratedProtocolMessageType('PlayerState', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSTATE,
  '__module__' : 'player_state_pb2'
  # @@protoc_insertion_point(class_scope:thegamblr.PlayerState)
  })
_sym_db.RegisterMessage(PlayerState)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017thegamblr/proto'
  _PLAYERSTATUS._serialized_start=325
  _PLAYERSTATUS._serialized_end=385
  _PLAYERROUNDRESULTS._serialized_start=45
  _PLAYERROUNDRESULTS._serialized_end=164
  _PLAYERSTATE._serialized_start=167
  _PLAYERSTATE._serialized_end=323
# @@protoc_insertion_point(module_scope)
