# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstage.proto\x12\tthegamblr*[\n\x05Stage\x12\x0c\n\x08PRE_FLOP\x10\x00\x12\x08\n\x04\x46LOP\x10\x01\x12\x08\n\x04TURN\x10\x02\x12\t\n\x05RIVER\x10\x03\x12\x12\n\x0eROUND_COMPLETE\x10\x04\x12\x11\n\rGAME_COMPLETE\x10\x05\x42\x11Z\x0fthegamblr/protob\x06proto3')

_STAGE = DESCRIPTOR.enum_types_by_name['Stage']
Stage = enum_type_wrapper.EnumTypeWrapper(_STAGE)
PRE_FLOP = 0
FLOP = 1
TURN = 2
RIVER = 3
ROUND_COMPLETE = 4
GAME_COMPLETE = 5


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017thegamblr/proto'
  _STAGE._serialized_start=26
  _STAGE._serialized_end=117
# @@protoc_insertion_point(module_scope)
